---
name: Release current version on Github

on:
  workflow_call:
    secrets:
      DEFAULT_CONFIG:
        required: true
  workflow_dispatch:

jobs:
  create-gh-release:
    name: Create github release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Get version
        id: get_version
        run: |
          version=$(npm version --json | jq -r '."oncall-slackbot"')
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
