---
name: Release current version on Github

on:
  workflow_call:
    secrets:
      DEFAULT_CONFIG:
        required: true
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: install deps
        run: bun i
      - name: install config
        run: echo '${{ secrets.DEFAULT_CONFIG }}' > config/default.json
      - name: run tests
        run: |
          bun test
  create-gh-release:
    name: Create github release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          version=$(npm version --json | jq -r '."oncall-slackbot"')
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
