---
name: Release new version

on:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: install deps
        run: bun i
      - name: install config
        uses: ttd2089/secret-file-action@1.0.0
        id: gpg-key-secret
        with:
          secret: ${{ secrets.DEFAULT_CONFIG }}
          b64-decode: false
          file: config/default.json
      - name: run tests
        run: bun test
  create-gh-release:
    name: Create github release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        run: |
          version=$(npm version --json | jq -r '."oncall-slackbot"')
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.version }}
          release_name: ${{ steps.bump.outputs.version }}
          draft: false
          prerelease: false
